Web:
  CMD: "./web-server --ip 127.0.0.1 --port 8080 --config_path ./conf/store_servers.conf" # 根据自己的实际需要更改
  URL: "http://localhost:8080"

Store: # 二选一开启即可
  2PC: 
    Status: true
    CMD:
      # 集群一
      - ./store-server --config_path ./conf/coordinator1.conf
      - ./store-server --config_path ./conf/participant101.conf
      - ./store-server --config_path ./conf/participant102.conf
      - ./store-server --config_path ./conf/participant103.conf
      # 集群二
      - ./store-server --config_path ./conf/coordinator2.conf
      - ./store-server --config_path ./conf/participant201.conf
      - ./store-server --config_path ./conf/participant202.conf
      - ./store-server --config_path ./conf/participant203.conf
  RAFT: 
    Status: true
    CMD:
      # 集群一
      - ./store-server --config_path ./conf/store101.conf
      - ./store-server --config_path ./conf/store102.conf
      - ./store-server --config_path ./conf/store103.conf
      - ./store-server --config_path ./conf/store104.conf
      # 集群二
      - ./store-server --config_path ./conf/store201.conf
      - ./store-server --config_path ./conf/store202.conf
      - ./store-server --config_path ./conf/store203.conf
      - ./store-server --config_path ./conf/store204.conf

Balancer:
  Status: true # 是否开启负载均衡器
  CMD: "./load-balancer --ip 127.0.0.1 --port 8080 --store_config_path ./conf/store_servers.conf --web_config_path ./conf/web_servers.conf" # 根据自己的实际需要更改
  URL: "http://localhost:8080"
  Web: # web-server的集群启动命令
    - "./web-server01 --ip 127.0.0.1 --port 8081 --config_path ./conf/store_servers.conf"
    - "./web-server02 --ip 127.0.0.1 --port 8082 --config_path ./conf/store_servers.conf"
    - "./web-server03 --ip 127.0.0.1 --port 8083 --config_path ./conf/store_servers.conf"

Static:
  Course: "./data/course.txt"
  Student: "./data/student.txt"
  RootPath: "/home/lab4" # 你的程序所在文件夹
  Build: "make"
  Clean: "make clean"
  Debug: false # 输出你的程序的输出
  HttpDebug: true # 输出http相关信息